### ISSUE TITLE
LogRecord array attributes

### ISSUE THREAD

**Issue by pavel-faltynek** [serilog/serilog-sinks-opentelemetry#144]
That's not an issue, rather a question.

We are using this sink with otel grpc exporter and the logging frontend does not show logeEvent's collection properties. Quick look at the code shows that `LogEvent` -> `LogRecord` transformation still preserves them as expected. But I've got lost with the heavily generated grpc code (initially working with decompiled code). Thus I'm unable to say the arrays disappear here or it is just an inability of the frontend (and its associated systems) to present LogRecord's array attributes.

Are the `LogEvent` collection properties (or `LogRecord` array attributes) supposed to work correctly and pass through the whole pipeline intact?

**Comment by julealgon** [comment]
> That's not an issue, rather a question.

@nblumhardt you should consider enabling `Discussions` in the repo and direct people there for questions. Helps with the noise in issues and allows people to subscribe just to one or the other.

Not a huge deal, just figured I'd mention it.

**Comment by nblumhardt** [comment]
Thanks @julealgon; I might update the issue tracker templates to match the other Serilog ones; we don't really have the time or interest in moderating broad discussions here, so unless something is a feature request or bug, we generally direct people to Stack Overflow.

@pavel-faltynek thanks for your message. The sink has full support for structured data, so probably best to check the capabilities of your collector/back end. If it turns out there's a bug or limitation here, a report would be most welcome, but I'll close this now as there's nothing we can action on it. Cheers!
