### ISSUE TITLE
Allow configuring OTEL_* settings from anywhere, not only environment

### ISSUE THREAD

**Issue by srogovtsev** [serilog/serilog-sinks-opentelemetry#151]
#141 (see also #12) has brought support for standard OpenTelemetry configuration (`OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` and so on), but it only consumes them from environment, while standard OpenTelemetry implementation in .NET allow consuming the same configuration options from passed `IConfiguration`, no matter where they are defined (which is handy for non-standard deployments). I propose we add some way to pass any configuration to the `OpenTelemetry` configuration method.

As I understand that adding `IConfiguration` would not be desirable due to an additional dependency, I propose we simply expose already existing `Func<string, string?>` configuration getter (which is very easily mappable to [`IConfiguration.Item[string]`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.item?view=net-8.0#microsoft-extensions-configuration-iconfiguration-item(system-string)), to allow for additional extensibility.

**Comment by mcdevmc** [comment]
Is there a way to make this solution work when reading Serilog configuration from appsettings.json?

When the WriteTo is configured in code, I can read the `OTEL_*` variables successfully from appsettings.json with the following:
```c#
builder.Services.AddSerilog((services, logging) =>
{
    logging.ReadFrom.Configuration(builder.Configuration)
        .ReadFrom.Services(services)
        .WriteTo.OpenTelemetry(options => { }, getConfigurationVariable: key => builder.Configuration[key]);
});
```
but not sure how/if the WriteTo can be configured in appsettings.json:
```json
{
  "Serilog": {
    "Using": [
      "Serilog.Sinks.Console",
      "Serilog.Sinks.OpenTelemetry"
    ],
    "MinimumLevel": {
      "Default": "Information",
      "Override": {
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "WriteTo": [
      { "Name": "Console" },
      {
        "Name": "OpenTelemetry",
        "Args": {
          "getConfigurationVariable": ?
        }
      }
    ],
    "Enrich": [ "FromLogContext" ]
  },
  "OTEL_EXPORTER_OTLP_ENDPOINT": "http://localhost:5341/ingest/otlp",
  "OTEL_EXPORTER_OTLP_PROTOCOL": "http/protobuf",
}
```
For now, the only solution I've been able to find is to explicitly duplicate the values into the Endpoint and Protocol Args for the sink. This is less ideal since I still need to keep the `OTEL_*` variables for trace logs, so I need to define the values twice.
